config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :public_keys, :controller => 'gitolite_public_keys'
match 'gitolite_hook' => 'gitolite_hook#index'

app/models/gitolite_public_key.rb
require 'open3'

class GitolitePublicKey < ActiveRecord::Base
  unloadable
  STATUS_ACTIVE = 1
  STATUS_LOCKED = 0

  belongs_to :user
  validates_uniqueness_of :title, :scope => :user_id
  validates_uniqueness_of :identifier, :score => :user_id
  validates_presence_of :title, :key, :identifier

  scope :active, {:conditions => {:active => GitolitePublicKey::STATUS_ACTIVE}}
  scope :inactive, {:conditions => {:active => GitolitePublicKey::STATUS_LOCKED}}

  validate :has_not_been_changed, :is_valid_key

  before_validation :set_identifier

  def has_not_been_changed
    unless new_record?
      %w(identifier key user_id).each do |attribute|
        errors.add(attribute, 'may not be changed') unless changes[attribute].blank?
      end
    end
  end

  def is_valid_key
    valid = check_key(key)
    if !valid
      begin
        # We try validating again, after adding a newline, since some 4096-bit
        # public keys fail validation when a newline isn't present
        key = "#{key}\n"
        valid = check_key(key)
        if !valid
          errors[:base] = "invalid key"
        else
          self.key = key
        end
      rescue
        errors[:base] = "invalid key"
      end
    end
  end

  def check_key(key)
    File.open('/tmp/check_key', 'w') {|f| f.write(key)}
    stdin, stdout, stderr = Open3.popen3('ssh-keygen -l -f /tmp/check_key')
    data = stdout.gets()
    hash_regex = /([0-9a-f][0-9a-f](:[0-9a-f][0-9a-f])+)/
    matching = hash_regex.match data
    File.delete('/tmp/check_key')
    if matching == nil
      false
    else
      true
    end
  end

  def set_identifier
    self.identifier ||= "#{self.user.login.underscore}@#{self.title.underscore}".gsub(/[^0-9a-zA-Z\-\_]/,'_')
  end

  def to_s ; title ; end

  def location
    self.title.underscore.gsub(/[^0-9a-zA-Z\-\_]/,'_')
  end

  def owner
    self.user.login.underscore.gsub(/[^0-9a-zA-Z\-\_]/,'_')
  end
end

app/controllers/gitolite_public_keys_controller.rb
class GitolitePublicKeysController < ApplicationController
  unloadable


  before_filter :require_login
  before_filter :set_user_variable
  before_filter :find_gitolite_public_key, :except => [:index, :new, :create]

  def index
    @status = if (session[:gitolite_public_key_filter_status]=params[:status]).nil?
      GitolitePublicKey::STATUS_ACTIVE
    elsif params[:status].blank?
        nil
    else
      params[:status].to_i != 0
    end

    scope = @user.gitolite_public_keys
    scope = scope.where(:active => true) if @status
    @gitolite_public_keys = scope.all(:order => 'active DESC, created_at DESC')


    respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => @gitolite_public_keys }
    end
  end

  def edit
  end

  def update
    if params[:public_key][:active]
      status = params[:public_key].delete(:active).to_i
      if status == GitolitePublicKey::STATUS_ACTIVE
        @gitolite_public_key.active = true
      elsif status == GitolitePublicKey::STATUS_LOCKED
        @gitolite_public_key.active = false
      end
    end

    if @gitolite_public_key.update_attributes(params[:public_key])
      flash[:notice] = l(:notice_public_key_updated)
      redirect_to url_for(:action => 'index', :status => session[:gitolite_public_key_filter_status])
    else
      render :action => 'edit'
    end
  end

  def new
    @gitolite_public_key = GitolitePublicKey.new(:user => @user)
  end

  def create
    @gitolite_public_key = GitolitePublicKey.new(params[:public_key].merge(:user => @user))
    if @gitolite_public_key.save
      flash[:notice] = l(:notice_public_key_added)
      redirect_to url_for(:action => 'index', :status => session[:gitolite_public_key_filter_status])
    else
      render :action => 'new'
    end
  end

  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @gitolite_public_key }
    end
  end

  protected

  def set_user_variable
    @user = User.current
  end

  def find_gitolite_public_key
    key = GitolitePublicKey.find_by_id(params[:id])
    if key and key.user == @user
      @gitolite_public_key = key
    elsif key
      render_403
    else
      render_404
    end
  end
end

app/helpers/gitolite_public_keys_helper.rb
module GitolitePublicKeysHelper
  def gitolite_public_keys_status_options_for_select(user, selected)
    key_count_by_active = user.gitolite_public_keys.count(:group => 'active').to_hash
    options_for_select([[l(:label_all), nil], 
                        ["#{l(:status_active)} (#{key_count_by_active[GitolitePublicKey::STATUS_ACTIVE].to_i})", GitolitePublicKey::STATUS_ACTIVE],
                        ["#{l(:status_locked)} (#{key_count_by_active[GitolitePublicKey::STATUS_LOCKED].to_i})", GitolitePublicKey::STATUS_LOCKED]], selected)
  end
end

app/views/gitolite_public_keys/_form.html.erb
<div class="box tabular">
	<p><%= f.text_field :title, :required => true %></p>
	<p><%= f.text_area :key, :required => true, :disabled => !@gitolite_public_key.new_record?, :style => 'width:99%;height:140px;', :label => :field_public_key %>
		<% if !@gitolite_public_key.new_record?%>
		<br/><em><%= l(:label_key_cannot_be_changed_please_create_new_key) %></em>
		<% end %>
	</p>
	<p><%= f.check_box :active %></p>
</div>

app/views/gitolite_public_keys/edit.html.erb
<h2><%= link_to l(:label_public_keys), public_keys_path %> &#187; <%= h @gitolite_public_key %></h2>
FOO
<% if @gitolite_public_key.errors.any? %>
  <ul>
    <% @gitolite_public_key.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= labelled_form_for :public_key, @gitolite_public_key, :url => { :action => "update" }, :html => { :method => :put}, :lang => current_language do |f| %>

	<%= render :partial => 'form', :locals => { :f => f } %>
	<%= submit_tag l(:button_save) %>
<% end %>

<% html_title(l(:label_public_keys)) -%>

app/views/gitolite_public_keys/index.html.erb
<h2><%= link_to l(:label_my_account), :controller => 'my', :action => 'account' %> &#187; <%=l(:label_public_keys)%></h2>

<% form_tag({}, :method => :get) do %>
<fieldset><legend><%= l(:label_filter_plural) %></legend>
<label><%= l(:field_status) %>:</label>
<%= select_tag 'status', gitolite_public_keys_status_options_for_select(@user, @status), :class => "small", :onchange => "this.form.submit(); return false;"  %>
<%= submit_tag l(:button_apply), :class => "small", :name => nil %>
</fieldset>
<% end %>
&nbsp;


<% if @gitolite_public_keys.any? %>

	<table class="list">
		<tr>
		    <th><%= l(:field_name) %></th>
		    <th><%= l(:field_created_on) %></th>
		    <th style="width:15%;"><%= l(:field_active) %></th>
		    <th align="center" style="width:10%;"> </th>
		</tr>
		<% @gitolite_public_keys.each do |key| %>
		<tr class="<%= cycle('odd', 'even') %>">
		    <td><%= link_to h(key), :action => 'edit', :id => key %></td>
			<td><%= format_time(key.created_at) %></td>
		    <td class="center" style="width:15%;"><%= image_tag('true.png') if key.active? %></td>
		    <td class="buttons">
				      <%= link_to l(key.active? ? :button_lock : :button_unlock), public_key_path(key, :public_key => {:active => key.active? ? GitolitePublicKey::STATUS_LOCKED : GitolitePublicKey::STATUS_ACTIVE}), :method => :put, :class => "icon #{key.active? ? 'icon-lock' : 'icon-unlock'}" %>
		    </td>
		</tr>
		<% end %>
	</table>

<% end %>

<p><%= link_to l(:label_enumeration_new), { :action => 'new'} %></p>

<% html_title(l(:label_public_keys)) -%>

app/views/gitolite_public_keys/new.html.erb
<h2><%= link_to l(:label_public_keys), public_keys_path %> &#187; <%=l(:label_public_key_new)%></h2>

<% if @gitolite_public_key.errors.any? %>
  <ul>
    <% @gitolite_public_key.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= labelled_form_for :public_key, @gitolite_public_key, :url => { :action => "create" }, :lang => current_language do |f| %>
	<%= render :partial => 'form', :locals => { :f => f } %>
	<%= submit_tag l(:button_create) %>
<% end %>

<% html_title(l(:label_public_keys)) -%>